<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LedManagerSetup</AssemblyName>
    <RootNamespace>LedManager.Setup</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LedManager.Core\LedManager.Core.csproj" />
  </ItemGroup>

</Project>
